### PR TITLE
Add more developer links in popup,html file

### PR DESCRIPTION
**Pull request by Dcode-k**
Screenshot from 2021-10-07 08-52-49

### CODE REVIEW

**Comment by Dcode-k** [comment]
@StarTrooper08 Please review my PR #4 and merge it.

**Comment by Dcode-k** [comment]
I will add more developers links in future.

**Comment by atharvashirdhankar** [comment]
Hey @Dcode-k the icons are too congested.
Try to make 2 rows and adjust those icons in 2 rows , 6 columns.

**Comment by Dcode-k** [comment]
@StarTrooper08 okk I will try it.

**Comment by Dcode-k** [comment]
@StarTrooper08  Please review the changes in PR #4 
Screenshot from 2021-10-07 11-59-26

**Comment by atharvashirdhankar** [comment]
Cool👍

**Comment by atharvashirdhankar** [comment]
Can you remove gmail from it.

**Pull request merged**
